### ISSUE TITLE
draw.begin() without clearing?

### ISSUE THREAD

**Issue by ra-martin** [Nazariglez/nae#48]
I tried using:

```rust
draw.begin(Color::TRANSPARENT);
```
 Sadly, this results in artifacts:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/15673326/108423089-b62b7080-7237-11eb-881c-31298cb1cbf6.png">

In comparison, if I use the following code:

```rust
pub fn begin_no_clear(&mut self) {
    let projection = match &self.gfx.render_target {
        Some(rt) => projection(rt.width(), rt.height(), true, 1.0),
        None => projection(self.gfx.width, self.gfx.height, false, self.dpi),
    };

    self.render_projection = projection;

    self.clear_options.color = None;
    self.gfx.begin(&self.clear_options);
}
```

The render looks like this:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/15673326/108423435-24703300-7238-11eb-8ddc-a027b14b95cd.png">

Maybe `draw.begin()` should take an `Option<Color>`?

**Comment by Nazariglez** [comment]
That makes sense to me, I'll look at it this weekend. 

Indeed I'm looking at the refactor that I have (on my laptop) in progress and I'm using an option for the color:
```
    pub fn begin(&mut self, color: Option<&Color>) {
        self.renderer
            .begin(color.map(|c| ClearOptions::new(*c)).as_ref());
    }
``` 

But it was because it was cleaner, I never realize that the Color::Transparent was glitchy. So it makes total sense to change the current API to use an option. Good catch!
